export enum ErrorCodes {
    BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
    BOARD_ALREADY_EXIST = 'BOARD_ALREADY_EXIST',

    COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND',
    COLUMN_ALREADY_EXIST = 'COLUMN_ALREADY_EXIST',

    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_ALREADY_EXIST = 'TASK_ALREADY_EXIST',

    TASK_USER_NOT_FOUND = 'TASK_USER_NOT_FOUND',

    TASK_MSG_NOT_FOUND = 'TASK_MSG_NOT_FOUND',

    DATA_NOT_FOUND = 'DATA_NOT_FOUND',
    DATA_ALREADY_EXIST = 'DATA_ALREADY_EXIST'
}