export enum ErrorCodes {
    BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
    BOARD_ALREADY_EXIST = 'BOARD_ALREADY_EXIST',

    COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND',
    COLUMN_ALREADY_EXIST = 'COLUMN_ALREADY_EXIST',

    DATA_NOT_FOUND = 'DATA_NOT_FOUND',
}